#!/usr/bin/env bash
set -euo pipefail

# store some directory variables.
current_dir=$PWD
root_dir=$(git rev-parse --show-toplevel)
stan_dir=$root_dir/stanfrontend

# store the name of the program
prog=${1##*/}
name=${prog%.*}
parent_dir="$(dirname -- "$(readlink -f -- "$1")")"

cd $root_dir

function echo_and_run {
    echo $@
    $@
}

# working directory is stan dir
cd stanfrontend


## ccomp doesn't compile down to object files, just asm
echo_and_run ccomp -dc -dclight -g3 -c $parent_dir/$name.stan && ccomp -c ${name}.s || exit 1

# compile generated printing functions
echo_and_run ccomp -g3 -I${stan_dir} -c ${parent_dir}/${name}_prelude.c

# build stanlib.o
# FIXME: getting an undefined symbol with ccomp -- not sure what happened all of a sudden
echo_and_run gcc -g3 -c stanlib.c -lm

# runtime is dependent on libstan, temporarily.
echo_and_run ccomp -g3 -I${stan_dir}  -c Runtime.c

# compile the final binary
echo_and_run ccomp -g3 -L${stan_dir} -L../out/lib/compcert -lm stanlib.o ${name}_prelude.o ${name}.o Runtime.o -o runit

# tell the user what to do next
echo "compiled! ./stanfrontend/runit INT"

