#!/usr/bin/env bash

root_dir=$(git rev-parse --show-toplevel)
cd $root_dir

rm -f *.s clightgen ccomp *.so *.o
rm -f compcert.ini compcert.config .depend .lia.cache

cd ./stanfrontend
rm -f *.s *.so runit *.vo *.vok *.glob *.vos *.s *.o

cd $root_dir

# comment out coq-proba dependcy in Makefile
awk -i inplace '/COQPROBA/, c++ == 3 {$0 = "#" $0} { print }' ./Makefile

make clean

# uncomment out coq-proba dependcy in Makefile
awk -i inplace '/COQPROBA/, c++ == 3 { gsub("^#+", "") } { print }' ./Makefile
