#!/usr/bin/env bash

root_dir=$(git rev-parse --show-toplevel)
cd $root_dir

rg --type coq '(admit|Admitted)\.' stanfrontend/*proof.v

if (( $? == 1 )); then
    exit 0
elif (( $? == 0 )); then
    exit 1
else
    exit $?
fi
