#!/usr/bin/env bash

set -e

# store some directory variables.
current_dir=$PWD
root_dir=$(git rev-parse --show-toplevel)
stan_dir=$root_dir/stanfrontend

# store the name of the program
prog=${1##*/}
name=${prog%.*}
parent_dir="$(dirname -- "$(readlink -f -- "$1")")"
cd $root_dir

# don't run this on c files
watchexec -e v,c,stan  --ignore $name.v --ignore $name.light.c "\make -j && make install && rm ccomp clightgen && (ccompstan $current_dir/$1 && echo 'compiled!' || echo 'failed!')"
